### ISSUE TITLE
Failed to compile.

### ISSUE THREAD

**Issue by Sikksens** [adriansteffan/discord-community-soundboard#15]
Hey there,

Having this issue when running frontend

```
Failed to compile.

./src/copied_config.js
  Line 13:16:  'configure' is not defined  no-undef

Search for the keywords to learn more about each error.
```

**Comment by adriansteffan** [comment]
There seems to have been a typo in the config js template. Just create a new config from the updated version and it should run fine.

Feel free to reopen if the issue persists!
